dist: trusty

language: java

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - openjdk6
  - openjdk7
  - openjdk8
  - oraclejdk11

before_script:
  - chmod +x gradlew
  - ./gradlew clean

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - ./gradlew jar
  - ./gradlew sourcesJar
  - ./gradlew jarWithDependencies
  - ./gradlew dokkaJavadocJar

deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      branch: master
      condition: $TRAVIS_JDK_VERSION = openjdk6
    file_glob: true
    file: build/libs/*.jar
    api_key:
      secure: x3hBpXaGN0P25chQTVXuGU7zNJyCYsMf7h7Rwl9EC7vK9tjcd1YxfzUjQNPfX7FIzt8qvszlBWtqP8ubCgsBHjSpPIjISFKskDd2Sr/5RpPdwRm+hK9oe4/p2KC54cDweZrbdHUu07JUVbQy0kOpipupLI0VlBo5D+V+Itx754oHgFCW7nuh+YgCc7AFcuMjbBP+7t+lhGclaCt4034ydjhmC65JDl1tI0CexJUz/BsGqFpKYzAkFC6X9vaLit1/6mRPHlRPkC7oVVsaTVLuz3emIRYEivj0eVYfqHsK6tFPeP95Q3vAutnUVhCmAFZtxPsLZz+jM9i7X+aDcHd1HZvqarQY0dcssFZ31oTG7S6uLkhY3Sv1PE8Cl5u4wwahbv1F3tn7FgjDsWVEuUeOg9RK6CdP2+uBfqVDEO6peS6ZptnRGcrj9h1+u90nfbr2/aKBl06wBU7eABVLWmCJ5YEfKVUjP2dt3Wly7kNcqVwJjpOjHwwJFT/6BT1SsN1ch9KWkktSQ3r/2X/DkUO38WzxVoT4T5v3aE0z1Z1QRvA3ZH51Dliquoku99tI0j1AQfXpwCtbZDwN+kqKpfPmbbUbInbF0TFxk/kE1C7M2oCr54DnUm/UX8KOVQwkfvcbDHJ2xXi6cRC12cVlnveXzUxr6bPu+z+VCaT2e61EV10=
